"""django_first URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

from first_app import views ## let's first include the views of our app
from django.urls import include ## copied from above

urlpatterns = [
    path('', views.index, name='index'), ## let's define our imported view as the index file in the main folder
    path('secreturl/', include('first_app.fake_urls')), ## now we can access this page using 2 urls
    path('help/', views.help, name='help'), ## now, let's create a second view in the same app (first_app)

    path('admin/', admin.site.urls), ## this was generated by django
]
